return {
  LOGIN = { text = 'Login', json_value = 'LOGIN', icon = '󰌾' },
  PASSWORD = { text = 'Password', json_value = 'PASSWORD', icon = '' },
  API_CREDENTIAL = { text = 'API Credential', json_value = 'API_CREDENTIAL', icon = '' },
  SERVER = { text = 'Server', json_value = 'SERVER', icon = '' },
  DATABASE = { text = 'Database', json_value = 'DATABASE', icon = '' },
  CREDIT_CARD = { text = 'Credit Card', json_value = 'CREDIT_CARD', icon = '' },
  MEMBERSHIP = { text = 'Membership', json_value = 'MEMBERSHIP', icon = '' },
  PASSPORT = { text = 'Passport', json_value = 'PASSPORT', icon = '' },
  SOFTWARE_LICENSE = { text = 'Software License', json_value = 'SOFTWARE_LICENSE', icon = '' },
  OUTDOOR_LICENSE = { text = 'Outdoor License', json_value = 'OUTDOOR_LICENSE', icon = '' },
  SECURE_NOTE = { text = 'Secure Note', json_value = 'SECURE_NOTE', icon = '󰎞' },
  WIRELESS_ROUTER = { text = 'Wireless Router', json_value = 'WIRELESS_ROUTER', icon = '' },
  BANK_ACCOUNT = { text = 'Bank Account', json_value = 'BANK_ACCOUNT', icon = '' },
  DRIVER_LICENSE = { text = 'Driver License', json_value = 'DRIVER_LICENSE', icon = '' },
  IDENTITY = { text = 'Identity', json_value = 'IDENTITY', icon = '' },
  REWARD_PROGRAM = { text = 'Reward Program', json_value = 'REWARD_PROGRAM', icon = '' },
  DOCUMENT = { text = 'Document', json_value = 'DOCUMENT', icon = '󰈙' },
  EMAIL_ACCOUNT = { text = 'Email Account', json_value = 'EMAIL_ACCOUNT', icon = '󰇮' },
  SOCIAL_SECURITY_NUMBER = { text = 'Social Security Number', json_value = 'SOCIAL_SECURITY_NUMBER', icon = '' },
  MEDICAL_RECORD = { text = 'Medical Record', json_value = 'MEDICAL_RECORD', icon = '' },
  SSH_KEY = { text = 'SSH Key', json_value = 'SSH_KEY', icon = '' },
  CUSTOM = { text = 'Custom', json_value = 'CUSTOM', icon = '' },
}
